[workspace]
resolver = "2"

members = [
    "smarthouse",
    "smarthouse_web",
    "socket_lib",
    "thermo_lib",
    "socket_bin_async",
    "socket_lib_async",
    "thermo_bin_async",
    "thermo_lib_async",
    "patterns",
]
